### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by geniusgogo** [cdk8s/cdk8s-markdown-to-html#1]
使用方法呢？

**Comment by ITyongzhen** [comment]
同问

**Comment by cdk8s-harvestmoon** [comment]
@geniusgogo @ITyongzhen 
1.先下载 node安装包, 安装 nodejs (https://nodejs.org/zh-cn/)  下载长期支持版安装.
2.如果不懂如何安装可以看(https://www.runoob.com/nodejs/nodejs-install-setup.html).
3.确保在命令行执行 npm -v 能看到输出版本号.
4.在项目根路径打开命令行执行 npm config set registry https://registry.npm.taobao.org (先切换到淘宝源,不然下载包很慢)
5. 在项目根路径执行 npm install (有时候因为各种原因,包可能下载不全,多执行几次 npm install)
6.执行完 npm install 接着在项目根路径执行 npm start (如果下载包没问题,编译完会自动打开浏览器,这是后就可以了)
7.0 总结就是 4 步
7.1 安装 node
7.2 执行 npm config set registry https://registry.npm.taobao.org
7.3 npm install
7.4 npm start

**Comment by cdk8s-harvestmoon** [comment]
如果想要把图片上传到自己的图床上面
需要修改 /src/utils/constant.js 这个文件里面有个图床上传地址,把它替换成自己的图床地址
不同图床需要自己去看该图床的上传开发文档
